pipeline {
    agent any

    stages {
        stage('Install Dependencies') {
            steps {
                bat 'bundle install'
            }
        }

        stage('Run UI Tests - Chrome') {
            steps {
                bat 'set BROWSER=chrome&& bundle exec ruby run_tests.rb'
            }
        }

        stage('Run UI Tests - Firefox') {
            steps {
                bat 'set BROWSER=firefox&& bundle exec ruby selenium_tests/buttons_test.rb'
            }
        }

        stage('Run API Tests') {
            steps {
                bat 'bundle exec ruby run_api_tests.rb'
            }
        }

        stage('Generate HTML Report') {
            steps {
                bat 'bundle exec ruby generate_report.rb'
            }
        }
    }

    post {
        always {
            archiveArtifacts artifacts: 'reports/*.html', allowEmptyArchive: true
            archiveArtifacts artifacts: 'allure-results/*', allowEmptyArchive: true
        }
    }
}