class ReportHelper

  def self.generate(total_tests, passed_tests, failed_tests)
    execution_date = Time.now.strftime("%Y-%m-%d %H:%M:%S")
    pass_rate = total_tests.zero? ? 0 : ((passed_tests.to_f / total_tests) * 100).round(2)

    html = <<~HTML
      <!DOCTYPE html>
      <html>
      <head>
        <meta charset="UTF-8">
        <title>QA Automation Report</title>
        <style>
          body {
            font-family: Arial, sans-serif;
            background-color: #f4f6f8;
            margin: 0;
            padding: 30px;
            color: #1f2937;
          }

          .container {
            max-width: 1000px;
            margin: auto;
          }

          .header {
            background-color: #0f172a;
            color: white;
            padding: 30px;
            border-radius: 10px;
            margin-bottom: 25px;
          }

          .card {
            background-color: white;
            padding: 25px;
            border-radius: 10px;
            margin-bottom: 25px;
            box-shadow: 0 2px 8px rgba(0,0,0,0.08);
          }

          .summary {
            display: grid;
            grid-template-columns: repeat(4, 1fr);
            gap: 15px;
          }

          .metric {
            background-color: #f9fafb;
            border: 1px solid #e5e7eb;
            border-radius: 8px;
            padding: 20px;
            text-align: center;
          }

          .metric h3 {
            margin: 0;
            font-size: 28px;
          }

          .passed {
            color: #15803d;
          }

          .failed {
            color: #b91c1c;
          }

          .rate {
            color: #1d4ed8;
          }

          table {
            width: 100%;
            border-collapse: collapse;
          }

          td {
            padding: 12px;
            border-bottom: 1px solid #e5e7eb;
          }

          footer {
            text-align: center;
            color: #6b7280;
            font-size: 14px;
            margin-top: 20px;
          }
        </style>
      </head>
      <body>
        <div class="container">
          <div class="header">
            <h1>QA Automation Report</h1>
            <p>Ruby Selenium QA Automation Framework</p>
            <p><strong>Execution Date:</strong> #{execution_date}</p>
          </div>

          <div class="card">
            <h2>Execution Summary</h2>

            <div class="summary">
              <div class="metric">
                <h3>#{total_tests}</h3>
                <p>Total Tests</p>
              </div>

              <div class="metric">
                <h3 class="passed">#{passed_tests}</h3>
                <p>Passed</p>
              </div>

              <div class="metric">
                <h3 class="failed">#{failed_tests}</h3>
                <p>Failed</p>
              </div>

              <div class="metric">
                <h3 class="rate">#{pass_rate}%</h3>
                <p>Pass Rate</p>
              </div>
            </div>
          </div>

          <div class="card">
            <h2>Framework Information</h2>

            <table>
              <tr>
                <td><strong>Framework</strong></td>
                <td>Ruby Selenium QA Automation Framework</td>
              </tr>
              <tr>
                <td><strong>Test Framework</strong></td>
                <td>Minitest</td>
              </tr>
              <tr>
                <td><strong>Browser Automation</strong></td>
                <td>Selenium WebDriver</td>
              </tr>
              <tr>
                <td><strong>API Testing</strong></td>
                <td>HTTParty</td>
              </tr>
            </table>
          </div>

          <footer>
            Generated by Ruby Selenium QA Automation Framework
          </footer>
        </div>
      </body>
      </html>
    HTML

    File.write("reports/test_report.html", html)
  end

end